// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Message actions
export const MESSAGE_SENT_SUCCESS = 'MESSAGE_SENT_SUCCESS';
export const START_FETCHING_MESSAGES = 'START_FETCHING_MESSAGES';
export const MESSAGES_RECEIVED_SUCCESS = 'MESSAGES_RECEIVED_SUCCESS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
//Room actions
export const ROOM_CREATED_SUCCESS = 'ROOM_CREATED_SUCCESS';
export const START_FETCHING_ROOMS = 'START_FETCHING_ROOMS';
export const START_FETCHING_ROOMS_MEMBERS = 'START_FETCHING_ROOMS_MEMBERS';
export const ROOMS_RECEIVED_SUCCESS = 'ROOMS_RECEIVED_SUCCESS';
export const ROOM_MEMBERS_RECEIVED_SUCCESS = 'ROOM_MEMBERS_RECEIVED_SUCCESS';
export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_MEMBER = 'ADD_ROOM_MEMBER';
export const ROOM_JOINT_SUCCESS = 'ROOM_JOINT_SUCCESS';
export const ROOM_LEAVE_SUCCESS = 'ROOM_LEAVE_SUCCESS';
